### ISSUE TITLE
May return incorrectly if used by multiple modules

### ISSUE THREAD

**Issue by amadsen** [gustavnikolaj/require-or#2]
The use of `module.parent` to determine the context from which you require (either by building out the path or using the parent module's require function - which should handle the path resolution for you anyway) will potentially have a problem is you try to use `require-or` from more than one module.

[`module.parent`](https://nodejs.org/api/modules.html#modules_module_parent) is the **first** module to require your module, so all subsequent uses of `require-or` will require in the context of the first module that required it in the process.

**Comment by gustavnikolaj** [comment]
Thanks for your feedback. I ended up not needing the module anyway, so I'll be pulling it back. Archiving the repo here on github and deprecating the released packages on npm. And closing your issue in the process :-)

Should anyone read this and wish to pick it up, please get in touch with me. Find my contact information on my profile.
